// The admin in Hebrew. Keys are the English labels exactly as written in the code.
export const HE = {
  '"See it on your wrist" with your own photograph': "\"ראו על פרק היד\" עם תמונה שלכם",
  "*Stars* around words set them in italic.": "*כוכביות* סביב מילים מטות אותן.",
  "1 AED in {c}": "דירהם אחד ב־{c}",
  "18K gold": "זהב 18K",
  "30 days": "30 ימים", "7 days": "7 ימים", "90 days": "90 ימים",
  "A WhatsApp, email or phone click means someone pressed the button. Whether they sent anything is not known.": "לחיצה על וואטסאפ, אימייל או טלפון פירושה שמישהו לחץ על הכפתור. לא ידוע אם נשלח משהו.",
  "A band of words (and a picture, if you like) between two chapters. Use them sparingly: the chapters are the event.": "פס של מילים (ותמונה, אם רוצים) בין שני פרקים. כדאי במשורה: הפרקים הם העיקר.",
  "A click is not a message received.": "לחיצה אינה הודעה שהתקבלה.",
  "A film from the library": "סרטון מהספרייה",
  "A full address starting with https://": "כתובת מלאה שמתחילה ב־https://",
  "A full copy of the content, its history, releases, the library's records, enquiries, customers, quotes, the team and the audit trail, as one compressed file. Kept privately; links work for ten minutes. Pictures stay in the library and are copied separately when restoring (see ADMIN_SETUP.md).": "עותק מלא של התוכן, ההיסטוריה שלו, הפרסומים, רשומות הספרייה, הפניות, הלקוחות, הצעות המחיר, הצוות ויומן הפעולות, בקובץ דחוס אחד. נשמר באופן פרטי; הקישורים פועלים עשר דקות. התמונות נשארות בספרייה ומועתקות בנפרד בעת שחזור (ראו ADMIN_SETUP.md).",
  "A note for the history (optional)": "הערה להיסטוריה (לא חובה)",
  "A page in the style of the house's documents: a title, an introduction, then headings, paragraphs, pictures and buttons. It gets its own address and, if you like, a link under Client care.": "דף בסגנון מסמכי הבית: כותרת, פתיח, ואחריהם כותרות, פסקאות, תמונות וכפתורים. יש לו כתובת משלו, ואם רוצים, קישור תחת שירות לקוחות.",
  "A price needs at least one amount.": "מחיר צריך לפחות סכום אחד.",
  "A product already uses this address.": "מוצר אחר כבר משתמש בכתובת הזו.",
  "A quote needs an amount and a date it is valid until.": "הצעת מחיר צריכה סכום ותאריך תוקף.",
  "A second step at sign-in: a six-digit code from an app such as Google Authenticator, 1Password or Microsoft Authenticator. Strongly advised for the owner.": "שלב שני בכניסה: קוד בן שש ספרות מאפליקציה כמו Google Authenticator, ‏1Password או Microsoft Authenticator. מומלץ מאוד לבעלים.",
  "A session is one visit in one browser tab: a random number kept until 30 minutes pass without activity. Nothing about the person is known.": "ביקור הוא כניסה אחת בלשונית דפדפן אחת: מספר אקראי שנשמר עד שעוברות 30 דקות ללא פעילות. דבר אינו ידוע על האדם.",
  "A set price": "מחיר קבוע",
  "A small bar at the foot of the screen that visitors can close.": "פס קטן בתחתית המסך שהמבקרים יכולים לסגור.",
  'A starting price ("From …")': "מחיר התחלתי (\"החל מ…\")",
  "A step counts a session once it has done it after the step before, within the period.": "שלב נספר לביקור שעשה אותו אחרי השלב הקודם, בתוך התקופה.",
  "About": "אודות",
  "About 155 characters. Now {n}.": "כ־155 תווים. כרגע {n}.",
  "About 60 characters.": "כ־60 תווים.",
  "About 60 characters. Now {n}.": "כ־60 תווים. כרגע {n}.",
  "Above the fold of its window": "בראש חלון התכשיט",
  "Account": "חשבון",
  "Accounts are created by invitation from the owner. There is no sign-up.": "חשבונות נפתחים בהזמנה מהבעלים. אין הרשמה עצמית.",
  "Action": "פעולה",
  "Active now: {n} sessions with activity in the last 5 minutes (not a count of people). Counting started {d}; latest event {w}.": "פעילים עכשיו: {n} ביקורים עם פעילות ב־5 הדקות האחרונות (לא מספר אנשים). הספירה החלה {d}; האירוע האחרון {w}.",
  "Add": "הוספה", "Add a band": "הוספת פס", "Add a block": "הוספת חלק", "Add a category": "הוספת קטגוריה", "Add a film from the library": "הוספת סרטון מהספרייה",
  "Add a link": "הוספת קישור", "Add a moved page": "הוספת דף שעבר", "Add a note": "הוספת הערה", "Add a paragraph": "הוספת פסקה", "Add a picture": "הוספת תמונה",
  "Add a row": "הוספת שורה", "Add a section": "הוספת סעיף", "Add photographs from the library": "הוספת תמונות מהספרייה", "Add the note": "הוספת ההערה",
  "Added": "נוסף",
  "Added, but under 1254 pixels across: it may look soft on large screens.": "נוסף, אבל ברוחב של פחות מ־1254 פיקסלים: הוא עלול להיראות רך במסכים גדולים.",
  "Added.": "נוסף.",
  "Admin": "ניהול", "Admin sections": "אזורי הניהול", "After": "אחרי",
  "Agreed": "הסכימו", "Agreed to receive news from SILAVU": "הסכימו לקבל עדכונים מ־SILAVU",
  "All": "הכול", "All enquiries": "כל הפניות", "Always shown": "מוצג תמיד", "Amount": "סכום", "Analytics": "נתוני ביקורים", "Announcement": "הודעה",
  "Anonymize": "הפיכה לאנונימי", "Anonymize this person?": "להפוך את האדם הזה לאנונימי?",
  "Anonymously without storing anything; allowing adds return visits": "באופן אנונימי ובלי לשמור דבר; אישור מוסיף ספירת ביקורים חוזרים",
  "Answer by": "מענה דרך", "Archive": "העברה לארכיון", "Archive this product?": "להעביר את המוצר לארכיון?", "Archived": "בארכיון",
  "Archived. Publish to take it off the site.": "הועבר לארכיון. פרסמו כדי להסיר אותו מהאתר.",
  "Archived: it will not appear on the site.": "בארכיון: הוא לא יופיע באתר.",
  "As quoted": "כפי שהוצע",
  "Ask the owner to invite you. If you were removed, your access ended at once.": "בקשו מהבעלים להזמין אתכם. אם הוסרתם, הגישה הסתיימה מיד.",
  "Assigned": "באחריות", "Assigned to": "באחריות", "Assigned to me": "באחריותי",
  "At least 10 characters.": "לפחות 10 תווים.", "At least 10 characters. A sentence you will remember is good.": "לפחות 10 תווים. משפט שתזכרו הוא בחירה טובה.",
  "At least one carat weight must be offered.": "יש להציע לפחות משקל קראט אחד.", "At least one metal must be offered.": "יש להציע לפחות מתכת אחת.",
  "At least one origin must be offered.": "יש להציע לפחות מקור אחד.", "At least one photograph is needed.": "נדרשת לפחות תמונה אחת.", "At least one shape must be offered.": "יש להציע לפחות צורה אחת.",
  "Audit trail": "יומן פעולות", "Authenticator app": "אפליקציית אימות", "Authenticator required": "נדרש אימות דו־שלבי", "Average time looking": "זמן צפייה ממוצע",
  "Back to products": "חזרה למוצרים", "Back to sign in": "חזרה לכניסה", "Back to the original": "חזרה לנוסח המקורי", "Back to the overview": "חזרה לסקירה", "Backups": "גיבויים",
  "Badge (optional, e.g. New)": "תווית (לא חובה, למשל חדש)",
  "Becomes {u}. It cannot be changed later without moving the page.": "יהיה {u}. אי אפשר לשנות אותה בהמשך בלי להעביר את הדף.",
  "Before": "לפני", "Black": "שחור", "Breadcrumbs": "נתיב", "Breakdown": "פירוט", "Build access to published content": "גישת הבנייה לתוכן המפורסם",
  "Build log": "יומן הבנייה", "Building the preview…": "בונים את התצוגה המקדימה…", "Building the site…": "בונים את האתר…",
  "Button": "כפתור", "Button (optional)": "כפתור (לא חובה)", "Button goes to": "הכפתור מוביל אל", "Button or link": "כפתור או קישור", "By": "לפי",
  "Came from": "הגיעו מ", "Can be reserved": "אפשר לשריין", "Cancel": "ביטול", "Caption": "כיתוב", "Caption (optional)": "כיתוב (לא חובה)", "Carats": "קראט",
  "Card face": "חזית הכרטיס", "Card's second side": "הצד השני של הכרטיס", "Categories": "קטגוריות", "Category": "קטגוריה", "Change": "שינוי",
  "Change the film": "החלפת הסרטון", "Change the password": "שינוי הסיסמה", "Change the picture": "החלפת התמונה", "Change this person's role?": "לשנות את התפקיד?",
  "Changed elsewhere": "שונה במקום אחר", "Channel setting": "שיבוץ ערוץ", "Chapters": "פרקים",
  "Chapters hidden on the live site cannot be shown in the preview until they are published:": "פרקים שמוסתרים באתר החי לא יופיעו בתצוגה המקדימה עד שיפורסמו:",
  "Checked": "נבדק", "Checking {f}…": "בודקים את {f}…", "Choose a film": "בחירת סרטון", "Choose a picture": "בחירת תמונה", "Choose photographs": "בחירת תמונות", "City": "עיר",
  "Click the picture to set the point that must stay in view when it is cropped.": "לחצו על התמונה כדי לסמן את הנקודה שתישאר בתמונה כשהיא נחתכת.",
  "Close": "סגירה", "Code": "קוד", "Collection to enquiry": "מהקולקציה לפנייה", "Colour of its window": "צבע החלון שלו", "Confirm": "אישור",
  "Confirmation email to the person who wrote": "אימייל אישור לפונה", "Connections": "חיבורים", "Contact": "יצירת קשר", "Content": "תוכן", "Continue": "המשך",
  "Copied when the quote was made on {d}; later product changes do not affect it.": "הועתק כשההצעה נוצרה ב־{d}; שינויים מאוחרים במוצר אינם משפיעים עליה.",
  "Cost": "עלות", "Could not load this.": "לא הצלחנו לטעון.",
  "Counted only for visitors who allowed it. Counting started {d}. Last event {w}. Active in the last 5 minutes: {n} sessions.": "נספר רק אצל מבקרים שאישרו. הספירה החלה {d}. האירוע האחרון {w}. פעילים ב־5 הדקות האחרונות: {n} ביקורים.",
  "Counting begins when the backend is connected and a visitor allows it. There is no earlier history to show.": "הספירה מתחילה כשהמערכת מחוברת ומבקר מאשר. אין היסטוריה קודמת להציג.",
  "Counting starts when the backend is connected and visitors allow it. There is no history from before that.": "הספירה מתחילה כשהמערכת מחוברת ומבקרים מאשרים. אין היסטוריה מלפני כן.",
  "Create": "יצירה", "Currency": "מטבע", "Customer": "לקוח", "Customer's copy": "העותק ללקוח", "Customers": "לקוחות", "Database and sign-in": "מסד נתונים וכניסה",
  "Delivery and care (optional)": "מסירה ושירות (לא חובה)", "Description (under the title in search results)": "תיאור (מתחת לכותרת בתוצאות החיפוש)",
  "Description for people who cannot see it": "תיאור לאנשים שאינם רואים את התמונה", "Description in search results": "תיאור בתוצאות החיפוש",
  "Description in search results (optional)": "תיאור בתוצאות החיפוש (לא חובה)", "Desktop": "מחשב", "Details": "פרטים", "Device": "מכשיר",
  "Diamond origin": "מקור היהלומים", "Diamond shapes": "צורות יהלום", "Diamonds": "יהלומים", "Done.": "בוצע.", "Download {n}": "הורדת {n}",
  "Draft saved, not live yet": "הטיוטה נשמרה, עדיין לא באתר", "Draft saved. Not live until you publish.": "הטיוטה נשמרה. היא לא באתר עד שתפרסמו.",
  "Drag to change the order of the collection. Changes are saved as drafts; publish to put them on the site.": "גררו כדי לשנות את סדר הקולקציה. השינויים נשמרים כטיוטה; פרסמו כדי להעלות אותם לאתר.",
  "Drop pictures or films here, or": "גררו לכאן תמונות או סרטונים, או", "Due today or overdue:": "להיום או באיחור:", "Duplicate": "שכפול", "Duplicate this product": "שכפול המוצר",
  "Each piece's title and description are set on its own page in Products. The sharing picture is og.jpg in the site's code.": "הכותרת והתיאור של כל תכשיט נקבעים בדף שלו במוצרים. תמונת השיתוף היא og.jpg בקוד האתר.",
  "Earlier versions": "גרסאות קודמות", "Email": "אימייל", "Email to the house when an enquiry arrives": "אימייל לבית כשמגיעה פנייה", "Empty: no call option.": "ריק: אין אפשרות שיחה.",
  "Enquiries": "פניות", "Enquiries are still saved; nobody is emailed.": "הפניות נשמרות בכל זאת; אף אחד לא מקבל אימייל.", "Enquiries saved": "פניות שנשמרו",
  "Enquiries saved come from the enquiries themselves, not from the counter, so they include visitors who did not allow counting.": "הפניות שנשמרו נספרות מהפניות עצמן ולא מהמונה, ולכן כוללות גם מבקרים שלא אישרו ספירה.",
  "Enter the amount in each currency you quote. Nothing is converted automatically and there are no live exchange rates.": "הזינו סכום בכל מטבע שבו אתם מציעים. דבר אינו מומר אוטומטית ואין שערי חליפין חיים.",
  "Events": "אירועים",
  "Every page goes back to how it was in that release, as a new release. Nothing is deleted; the versions in between stay in the history.": "כל דף חוזר למצבו באותו פרסום, כפרסום חדש. דבר אינו נמחק; הגרסאות שבין לבין נשארות בהיסטוריה.",
  "Every sensitive action: who, what, when. It cannot be edited or deleted, by anyone.": "כל פעולה רגישה: מי, מה ומתי. אי אפשר לערוך או למחוק אותה, לאף אחד.",
  "Every sentence, label and button on the home page, in English and Hebrew. Product words are edited in Products, the documents in Policies. Leave a field as it is to keep the original.": "כל משפט, תווית וכפתור בדף הבית, באנגלית ובעברית. מילות המוצרים נערכות במוצרים, והמסמכים במדיניות. השאירו שדה כמו שהוא כדי לשמור על הנוסח המקורי.",
  "Everything is live.": "הכול באתר.", "Everything is translated": "הכול מתורגם", "Everything saved is live.": "כל מה שנשמר נמצא באתר.",
  "Export CSV": "ייצוא CSV", "Export days (CSV)": "ייצוא לפי ימים (CSV)", "Export ready.": "הייצוא מוכן.", "Export this table (CSV)": "ייצוא הטבלה (CSV)", "Exports": "ייצואים",
  "Extra links": "קישורים נוספים", "Features": "אפשרויות", "Field": "שדה", "Figure {n}": "נתון {n}", "Figures (AED)": "נתונים (בדירהם)", "Filled in from the price below.": "ממולא מהמחיר שלמטה.",
  "Film": "סרטון", "Film description": "תיאור הסרטון", "Films": "סרטונים", "Find": "חיפוש", "Find a text": "חיפוש טקסט", "Find the other record": "חיפוש הרשומה האחרת",
  "First button": "כפתור ראשון", "First time here": "פעם ראשונה כאן", "First wrote {d}": "פנו לראשונה ב־{d}", "Folder": "תיקייה", "Follow up on": "מעקב בתאריך",
  "Footer, under Explore": "בתחתית, תחת גלו", "For": "עבור", "For the team only. Never shown to the customer.": "לצוות בלבד. לעולם לא מוצג ללקוח.", "For {n}": "עבור {n}",
  "Forgot your password?": "שכחתם את הסיסמה?", "Four short figures; the last is always the price.": "ארבעה נתונים קצרים; האחרון הוא תמיד המחיר.", "From": "מתאריך",
  "Funnels": "משפכים", "Gallery": "גלריה", "Go back to this version?": "לחזור לגרסה הזו?", "Goes to": "מוביל אל", "Goes to (optional)": "מוביל אל (לא חובה)",
  "Good to see you, {name}": "טוב לראות אותך, {name}", "Handling": "טיפול", "Heading": "כותרת", "Hidden": "מוסתר",
  "Hidden products keep their page out of the site and the sitemap.": "מוצרים מוסתרים אינם מופיעים באתר ובמפת האתר.",
  "Hiding The Line also removes its menu links and the try-on.": "הסתרת הקו מסירה גם את הקישורים אליו בתפריט ואת המדידה על היד.",
  "History": "היסטוריה", "History & backups": "היסטוריה וגיבויים", "Home chapters": "פרקי דף הבית", "How these are counted": "איך זה נספר", "How visits are counted": "איך נספרים ביקורים",
  "If an older version of a page still uses it, it is hidden from the library but kept, so that version can be restored.": "אם גרסה ישנה של דף עדיין משתמשת בו, הוא מוסתר מהספרייה אבל נשמר, כדי שאפשר יהיה לשחזר את אותה גרסה.",
  "If that address has an account, a link to set a new password is on its way. It works once and expires within an hour.": "אם לכתובת הזו יש חשבון, קישור לבחירת סיסמה חדשה בדרך. הוא פועל פעם אחת ופג תוך שעה.",
  "Import the current site": "ייבוא האתר הנוכחי", "Imported {n} documents from the live site.": "יובאו {n} מסמכים מהאתר החי.",
  "Inbox for enquiries (when the backend is not used)": "תיבת הדואר לפניות (כשהמערכת אינה מחוברת)", "Internal": "פנימי", "Internal note (never on their copy)": "הערה פנימית (לעולם לא בעותק שלהם)",
  "Introduction": "פתיח", "Invitation sent to {e}.": "ההזמנה נשלחה אל {e}.", "Invite someone": "הזמנת איש צוות",
  "It applies to their next request, and they are signed out everywhere.": "זה חל מהפעולה הבאה שלהם, והם מנותקים מכל מקום.",
  "It becomes the draft (a new version; nothing is lost). Publish to put it on the site.": "היא תהפוך לטיוטה (גרסה חדשה; דבר לא אובד). פרסמו כדי להעלות אותה לאתר.",
  "It goes on the public site with the next build, in both languages, wherever it appears.": "זה עולה לאתר הציבורי בבנייה הבאה, בשתי השפות, בכל מקום שבו זה מופיע.",
  "It has diamonds (the window promises stone reports)": "יש בו יהלומים (החלון מבטיח תעודות לאבנים)",
  "It is archived, not deleted. Publish to take it down.": "הוא מועבר לארכיון ולא נמחק. פרסמו כדי להוריד אותו.",
  "It leaves the site with the next publish. Nothing is deleted: you can restore it, and older quotes keep their copy.": "הוא יוסר מהאתר בפרסום הבא. דבר אינו נמחק: אפשר לשחזר אותו, והצעות מחיר קודמות שומרות את העותק שלהן.",
  "It starts hidden. Fill it in, preview it, then show it and publish.": "הוא מתחיל מוסתר. מלאו את הפרטים, צפו בתצוגה מקדימה, ואז הציגו ופרסמו.",
  "Its address": "הכתובת שלו", "Its address on the site": "הכתובת שלו באתר", "Ivory": "שנהב",
  "JPEG, PNG, WebP or AVIF pictures, MP4 or WebM films, up to 50 MB each. For product photographs, 1254 pixels or more on the short side.": "תמונות JPEG, ‏PNG, ‏WebP או AVIF, סרטוני MP4 או WebM, עד 50MB כל אחד. לצילומי מוצר, 1254 פיקסלים ומעלה בצלע הקצרה.",
  "Keep mine on top of theirs": "לשמור את שלי על גבי שלהם", "Keep visit records for (days)": "לשמור נתוני ביקורים (ימים)", "Kind": "סוג", "Lab-grown": "מעבדה", "Label": "תווית",
  "Language of the admin": "שפת הניהול", "Languages & SEO": "שפות וחיפוש", "Latest release": "הפרסום האחרון",
  "Like pieces/old-name/ (no leading slash, ending in /).": "למשל pieces/old-name/ (בלי לוכסן בהתחלה, עם / בסוף).",
  "Listed under Client care in the footer": "מופיע תחת שירות לקוחות בתחתית", "Live on the site": "באתר", "Load their version": "טעינת הגרסה שלהם", "Loading…": "טוען…", "Look": "מראה",
  "Made with configurator version {n}; kept as it was.": "נוצר בגרסה {n} של כלי העיצוב; נשמר כפי שהיה.", "Make a quote": "הכנת הצעת מחיר", "Make an export now": "ייצוא עכשיו",
  "Make release {n} current again?": "להחזיר את פרסום {n} לאתר?", "Making, base": "עבודה, בסיס", "Mark as sent": "סימון כנשלחה", "Mark as sent?": "לסמן כנשלחה?", "Marketing": "דיוור",
  "Media": "מדיה", "Media library": "ספריית מדיה", "Menu": "תפריט", "Menus": "תפריטים", "Merge into {n}": "מיזוג אל {n}", "Merge two records": "מיזוג שתי רשומות",
  "Merge with another record…": "מיזוג עם רשומה אחרת…", "Merged.": "מוזג.", "Message": "הודעה", "Metal": "מתכת", "Metals": "מתכות", "Most viewed pieces": "התכשיטים שנצפו הכי הרבה",
  "Move down": "הזזה למטה", "Move up": "הזזה למעלה", "Moved pages": "דפים שעברו", "Name": "שם", "Name (as on the card)": "שם (כמו בכרטיס)", "Natural": "טבעי",
  "New address": "כתובת חדשה", "New page": "דף חדש", "New password": "סיסמה חדשה", "New product": "מוצר חדש", "Newer": "חדשים יותר", "No": "לא",
  "No Hebrew yet: the Hebrew page will show nothing here": "אין עדיין עברית: הדף בעברית לא יציג כאן דבר",
  "No authenticator is set up on this account.": "לא הוגדר אימות דו־שלבי בחשבון הזה.", "No customers match.": "אין לקוחות מתאימים.", "No differences.": "אין הבדלים.",
  "No enquiries match.": "אין פניות מתאימות.", "No enquiries yet.": "אין עדיין פניות.", "No exports yet.": "אין עדיין ייצואים.",
  "No film. A film is shown first in the gallery on the piece's page.": "אין סרטון. סרטון מוצג ראשון בגלריה בדף התכשיט.",
  "No notes yet.": "אין עדיין הערות.", "No piece from the collection.": "לא תכשיט מהקולקציה.", "No preference": "אין העדפה", "No quotes yet.": "אין עדיין הצעות מחיר.",
  "No releases yet.": "אין עדיין פרסומים.", "No versions yet.": "אין עדיין גרסאות.", "No visits counted yet.": "עדיין לא נספרו ביקורים.", "Nobody": "אף אחד", "None": "ללא", "None.": "אין.",
  "Not agreed: reply to this enquiry only": "לא הסכימו: מענה לפנייה הזו בלבד", "Not at all": "בכלל לא", "Not found.": "לא נמצא.", "Not in the collection grid": "לא בגריד הקולקציה",
  'Not shown: the builder says "Price on request"': "לא מוצג: כלי העיצוב אומר \"מחיר לפי בקשה\"", "Not used on any page.": "לא בשימוש באף דף.",
  "Note to the customer (on their copy)": "הערה ללקוח (בעותק שלו)", "Notes": "הערות", "Nothing has been published from the admin yet.": "עדיין לא פורסם דבר מהניהול.",
  "Nothing here yet.": "אין כאן עדיין דבר.", "Nothing in this period.": "אין נתונים בתקופה הזו.", "Number": "מספר", "Off": "כבוי", "Old address": "כתובת ישנה", "Older": "ישנים יותר",
  "Older versions use it {n} times; it is kept for them.": "גרסאות ישנות משתמשות בו {n} פעמים; הוא נשמר עבורן.", "On": "פעיל", "On the site": "באתר", "One line": "שורה אחת",
  "Only accounts the house has confirmed. An empty address shows nothing and claims nothing.": "רק חשבונות שהבית אישר. כתובת ריקה אינה מציגה דבר ואינה טוענת דבר.",
  "Only after the visitor allows it (recommended)": "רק אחרי שהמבקר מאשר (מומלץ)",
  "Only details people gave through the site or that the team entered. Marketing permission is separate from answering an enquiry.": "רק פרטים שאנשים מסרו דרך האתר או שהצוות הזין. הסכמה לדיוור נפרדת ממענה לפנייה.",
  "Only enquiries the site saved are here. Clicks on WhatsApp, email or phone are counted in Analytics; they are not messages.": "כאן רק פניות שהאתר שמר. לחיצות על וואטסאפ, אימייל או טלפון נספרות בנתוני הביקורים; הן אינן הודעות.",
  "Only missing": "רק חסרים", "Only the owner changes how visits are counted.": "רק הבעלים משנים את אופן ספירת הביקורים.",
  "Only the owner sees this. It is never published and never part of a quote's customer copy.": "רק הבעלים רואים זאת. זה לעולם לא מתפרסם ואינו חלק מהעותק ללקוח.",
  "Only tick this if they asked for it.": "סמנו רק אם ביקשו זאת.", "Open": "פתוחות", "Open an email to {n}": "פתיחת אימייל אל {n}",
  'Open an enquiry and choose "Make a quote".': "פתחו פנייה ובחרו \"הכנת הצעת מחיר\".", "Open the record it was merged into": "פתיחת הרשומה שאליה מוזגה",
  "Open your authenticator app and type the six digits it shows for SILAVU.": "פתחו את אפליקציית האימות והקלידו את שש הספרות שהיא מציגה עבור SILAVU.",
  "Opens on": "נפתח על", "Order saved. Publish to change it on the site.": "הסדר נשמר. פרסמו כדי לשנות אותו באתר.", "Origin": "מקור", "Other currencies": "מטבעות נוספים",
  "Overview": "סקירה", "Page text": "טקסטים בדפים", "Pages": "דפים", "Pages & text": "דפים וטקסטים", "Pages viewed": "דפים שנצפו", "Paragraph": "פסקה",
  "Parts written as {{…}} are filled in by the site with the sentence that is true for how it is set up (where enquiries go, what is counted). Leave them in place.": "חלקים שכתובים כ־{{…}} ממולאים על ידי האתר במשפט הנכון לאופן שבו הוא מוגדר (לאן הולכות פניות, מה נספר). השאירו אותם במקומם.",
  "Password": "סיסמה", "People are only ever added by invitation. Nobody can give themselves a role.": "אנשים מצטרפים רק בהזמנה. אף אחד לא יכול להעניק לעצמו תפקיד.",
  "Per stone": "לכל אבן", "Person": "איש צוות", "Phone": "טלפון", "Phone number": "מספר טלפון", "Photographed on white": "צולם על רקע לבן", "Photographs & film": "תמונות וסרטון",
  "Picture": "תמונה", "Picture description": "תיאור התמונה", "Pictures": "תמונות",
  "Pictures and films for products, pages and bands. A file in use cannot be deleted.": "תמונות וסרטונים למוצרים, לדפים ולפסים. קובץ שנמצא בשימוש אינו ניתן למחיקה.",
  "Piece": "תכשיט", "Piece (e.g. knot)": "תכשיט (למשל knot)", "Placed after": "ממוקם אחרי", "Plain name, English (for enquiries and search)": "שם פשוט באנגלית (לפניות ולחיפוש)",
  "Plain name, Hebrew": "שם פשוט בעברית", "Platinum": "פלטינה", "Policies": "מדיניות", "Prefers": "מעדיפים", "Preview": "תצוגה מקדימה", "Preview this chapter": "תצוגה מקדימה של הפרק",
  "Price": "מחיר", "Price & visibility": "מחיר והצגה", "Price on request": "מחיר לפי בקשה", "Print or save as PDF": "הדפסה או שמירה כ־PDF",
  "Privacy, Terms and the other documents in the footer.": "פרטיות, תנאים ושאר המסמכים שבתחתית.", "Products": "מוצרים", "Products & collection": "מוצרים וקולקציה",
  "Publish": "פרסום", "Publish ({n})": "פרסום ({n})", "Publish the selected changes": "פרסום השינויים שנבחרו", "Publish this now?": "לפרסם עכשיו?", "Published": "פורסם",
  "Published in the database, but the site build did not start: {e}. Retry from History.": "פורסם במסד הנתונים, אבל בניית האתר לא התחילה: {e}. נסו שוב מההיסטוריה.",
  "Published. The site is rebuilding; it is usually live in two to four minutes.": "פורסם. האתר נבנה מחדש; בדרך כלל זה באוויר תוך שתיים עד ארבע דקות.",
  "Publishing": "פרסום", "Publishing to the site (GitHub)": "פרסום לאתר (GitHub)",
  "Put *stars* around the part shown in the piece's colour, e.g. SILAVU *MOMENT*.": "הקיפו ב*כוכביות* את החלק שמוצג בצבע התכשיט, למשל SILAVU *MOMENT*.",
  "QR code for the authenticator app": "קוד QR לאפליקציית האימות", "Quotes": "הצעות מחיר",
  "Quotes are made from an enquiry. Each keeps a copy of the piece and the design as they were.": "הצעות מחיר נוצרות מפנייה. כל הצעה שומרת עותק של התכשיט והעיצוב כפי שהיו.",
  "Reading {f}…": "קוראים את {f}…", "Received {w} (Israel time) · written in {l}": "התקבלה {w} (שעון ישראל) · נכתבה ב{l}",
  "Records older than the period set in Settings are deleted.": "רשומות ישנות מהתקופה שנקבעה בהגדרות נמחקות.", "Ref.": "מס׳", "Reference (SKU)": "מק״ט", "Reference size (ct)": "גודל ייחוס (קראט)",
  "Release {n} is recorded.": "פרסום {n} נרשם.", "Releases": "פרסומים", "Remove": "הסרה", "Remove from the library": "הסרה מהספרייה", "Remove from the library?": "להסיר מהספרייה?",
  "Remove it from those pages first": "הסירו אותו קודם מהדפים האלה", "Remove the film": "הסרת הסרטון", "Remove the picture": "הסרת התמונה", "Remove this authenticator?": "להסיר את האימות הדו־שלבי?",
  "Remove this link from the page": "הסרת הקישור מהדף", "Remove {n}?": "להסיר את {n}?", "Removed from the library.": "הוסר מהספרייה.", "Removed.": "הוסר.",
  "Replace everywhere": "החלפה בכל מקום", "Replace in the drafts": "החלפה בטיוטות", "Replace it everywhere…": "החלפה בכל מקום…", "Replaced by a newer release": "הוחלף בפרסום חדש יותר",
  "Replaced in {n} drafts. Preview them, then publish.": "הוחלף ב־{n} טיוטות. צפו בהן בתצוגה מקדימה ואז פרסמו.", "Required": "חובה", "Reset your password": "איפוס סיסמה",
  "Restore": "שחזור", "Restore this release": "שחזור הפרסום הזה", "Restored as the draft.": "שוחזר כטיוטה.", "Restored in the database; the build did not start: {e}": "שוחזר במסד הנתונים; הבנייה לא התחילה: {e}",
  "Restored release {n}": "שוחזר פרסום {n}", "Restored. Publish to show it again.": "שוחזר. פרסמו כדי להציג אותו שוב.", "Restored. The site is rebuilding.": "שוחזר. האתר נבנה מחדש.",
  "Returning browsers (with consent)": "דפדפנים חוזרים (בהסכמה)",
  "Returning browsers are counted only for visitors who allowed it; the same person on two devices counts twice.": "דפדפנים חוזרים נספרים רק אצל מבקרים שאישרו; אותו אדם בשני מכשירים נספר פעמיים.",
  "Robots that say who they are, and the admin's own browser, are left out. Robot detection is never perfect.": "רובוטים שמזדהים ככאלה, והדפדפן של הניהול עצמו, אינם נספרים. זיהוי רובוטים לעולם אינו מושלם.",
  "Role": "תפקיד", "Role changed.": "התפקיד שונה.", "Round to (AED)": "עיגול ל־(דירהם)", "Save": "שמירה", "Save draft": "שמירת טיוטה", "Save the password": "שמירת הסיסמה",
  "Saved.": "נשמר.", "Saved. Pages that use it change when they are next published.": "נשמר. דפים שמשתמשים בו ישתנו בפרסום הבא שלהם.",
  "Saving and publishing are done. The site rebuilds itself from what you published; it is usually live within two to four minutes. If the build fails, the site keeps showing the previous version and nothing you published is lost.": "השמירה והפרסום הסתיימו. האתר נבנה מחדש ממה שפרסמתם; בדרך כלל זה באוויר תוך שתיים עד ארבע דקות. אם הבנייה נכשלת, האתר ממשיך להציג את הגרסה הקודמת ושום דבר שפרסמתם לא אובד.",
  "Saving…": "שומרים…", "Scan this with the app, or type the key into it by hand. Then type the six digits it shows.": "סרקו את זה באפליקציה, או הקלידו בה את המפתח ידנית. אחר כך הקלידו את שש הספרות שהיא מציגה.",
  "Search": "חיפוש", "Search and sharing": "חיפוש ושיתוף", "Search name, email, phone, reference, city": "חיפוש לפי שם, אימייל, טלפון, מספר פנייה, עיר", "Search the library": "חיפוש בספרייה",
  "Second button": "כפתור שני", "Send the invitation": "שליחת ההזמנה", "Send the link": "שליחת הקישור",
  "Separated by commas, e.g. 2, 4, 6, 8, 10, 15, 20. An enquiry outside {a}–{b} ct is refused.": "מופרדים בפסיקים, למשל 2, 4, 6, 8, 10, 15, 20. פנייה מחוץ לטווח {a}–{b} קראט נדחית.",
  "Sessions": "ביקורים", "Sessions per day": "ביקורים ביום", "Sessions per day (Israel time). Dots mark days with saved enquiries.": "ביקורים ביום (שעון ישראל). נקודות מסמנות ימים עם פניות שנשמרו.",
  "Sessions that sent an enquiry": "ביקורים שבהם נשלחה פנייה", "Set a new password": "בחירת סיסמה חדשה", "Set on": "נקבע ב", "Set up an authenticator": "הגדרת אימות דו־שלבי", "Settings": "הגדרות",
  "Shape": "צורה", "Short line under the title on its page": "שורה קצרה מתחת לכותרת בדף שלו", "Show a short announcement on the home page": "הצגת הודעה קצרה בדף הבית",
  "Showing the first 200; use Find to narrow.": "מוצגים 200 הראשונים; השתמשו בחיפוש כדי לצמצם.", "Shown": "מוצג", "Shown in the collection": "מוצג בקולקציה",
  'Shown on every page and used for "write to us" links.': "מוצגת בכל דף ומשמשת לקישורי \"כתבו לנו\".", "Shown on the site as an estimate": "מוצג באתר כהערכה", "Shown on the site in": "מוצג באתר ב",
  "Shown to the team": "מוצג לצוות", "Sign in": "כניסה", "Sign out": "יציאה", "Since": "מאז", "Since {d}": "מאז {d}", "Size": "גודל", "Size curve": "עקומת גודל", "Sizes": "מידות",
  "Skip to content": "דילוג לתוכן", "Small heading above": "כותרת קטנה מעל", "Small heading above (optional)": "כותרת קטנה מעל (לא חובה)", "Social accounts": "רשתות חברתיות", "Someone": "מישהו",
  "Someone else changed this quote. Reload to see their version.": "מישהו אחר שינה את ההצעה. טענו מחדש כדי לראות את הגרסה שלו.",
  "Someone else saved this page meanwhile. Your version is kept; reload to see theirs.": "מישהו אחר שמר את הדף בינתיים. הגרסה שלכם נשמרה; טענו מחדש כדי לראות את שלו.",
  "Source (e.g. instagram.com)": "מקור (למשל instagram.com)",
  "Sources: the referring site's name, or the utm_source of a campaign link. Direct means neither was given.": "מקורות: שם האתר המפנה, או ה־utm_source של קישור קמפיין. ישיר פירושו שלא נמסר אף אחד מהם.",
  "Specification": "מפרט", "Stage": "שלב", "Start the build again": "הפעלת הבנייה מחדש", "State": "מצב", "Status": "סטטוס", "Supplier": "ספק", "Tab title": "כותרת הלשונית",
  "Tag": "תגית", "Tags": "תגיות", "Tags (comma separated)": "תגיות (מופרדות בפסיקים)", "Take this page off the site?": "להוריד את הדף מהאתר?", "Team": "צוות", "Text": "טקסט", "Text bands": "פסי טקסט",
  "That code is not right, or it has just changed. Try the new one.": "הקוד לא נכון, או שהוא התחלף זה עתה. נסו את החדש.",
  "That email and password do not match an account.": "האימייל והסיסמה אינם תואמים לחשבון.", "The Line": "הקו", "The Line to enquiry": "מהקו לפנייה",
  "The admin is not connected yet": "הניהול עדיין לא מחובר",
  "The amount and the specification are then fixed. Send the customer's copy yourself (print it to PDF or open the email below); nothing is sent automatically.": "מעכשיו הסכום והמפרט קבועים. שלחו את העותק ללקוח בעצמכם (הדפיסו ל־PDF או פתחו את האימייל שלמטה); דבר אינו נשלח אוטומטית.",
  "The authenticator is set up. You will be asked for a code when you sign in.": "האימות הדו־שלבי הוגדר. תתבקשו להזין קוד בכל כניסה.",
  "The build did not start: {e}": "הבנייה לא התחילה: {e}", "The build failed: the site still shows the previous version": "הבנייה נכשלה: האתר עדיין מציג את הגרסה הקודמת", "The build was started again.": "הבנייה הופעלה מחדש.",
  "The builder shows an estimate only when these figures are marked approved, carry the date they were set, and that date is recent enough. Otherwise it says the price is given on request. An estimate is never a quote; the enquiry never stores it as a price.": "כלי העיצוב מציג הערכה רק כשהנתונים האלה מסומנים כמאושרים, נושאים את התאריך שבו נקבעו, והתאריך עדכני מספיק. אחרת הוא אומר שהמחיר ניתן לפי בקשה. הערכה לעולם אינה הצעת מחיר; הפנייה לעולם אינה שומרת אותה כמחיר.",
  "The chapters are a designed sequence and keep their order. Those marked may be hidden; every link to a hidden chapter is removed with it.": "הפרקים הם רצף מעוצב ושומרים על הסדר. את המסומנים אפשר להסתיר; כל קישור לפרק מוסתר מוסר יחד איתו.",
  "The database is empty. Bring in the site exactly as it is now; from then on the admin is where it changes.": "מסד הנתונים ריק. ייבאו את האתר בדיוק כפי שהוא עכשיו; מכאן והלאה השינויים נעשים בניהול.",
  "The diamonds (optional)": "היהלומים (לא חובה)",
  "The email to the house about this enquiry was not sent ({why}). The enquiry itself is saved here.": "האימייל לבית על הפנייה הזו לא נשלח ({why}). הפנייה עצמה שמורה כאן.",
  "The estimate": "ההערכה", "The existing menu items are edited in Page text (their words and where they go, or removed). Add new ones here.": "פריטי התפריט הקיימים נערכים בטקסטים בדפים (המילים שלהם ולאן הם מובילים, או הסרה). הוסיפו כאן חדשים.",
  'The filter buttons above the collection. "All" always comes first. A product shows under the category it names.': "כפתורי הסינון מעל הקולקציה. \"הכול\" תמיד ראשון. מוצר מוצג תחת הקטגוריה שהוא מציין.",
  "The first one filled in": "הראשון שמולא",
  "The first photograph is the card's face, the second is what it turns to, and all of them make the gallery. Photographs of 1254 pixels or more stay sharp on every screen.": "התמונה הראשונה היא חזית הכרטיס, השנייה היא מה שהוא מתהפך אליו, וכולן יחד הן הגלריה. תמונות של 1254 פיקסלים ומעלה נשארות חדות בכל מסך.",
  "The home page": "דף הבית", "The house's email address": "כתובת האימייל של הבית", "The letter": "המכתב", "The list of page texts is missing from this build of the admin.": "רשימת הטקסטים בדפים חסרה בגרסה הזו של הניהול.",
  "The name is needed in both languages.": "השם נדרש בשתי השפות.", "The owner has not imported the site's content yet.": "הבעלים עדיין לא ייבאו את תוכן האתר.",
  "The owner requires an authenticator app for your account. Set it up in Account, then sign in again.": "הבעלים דורשים אימות דו־שלבי לחשבון שלכם. הגדירו אותו בחשבון ואז היכנסו שוב.",
  "The photograph never leaves the visitor's device.": "התמונה לעולם אינה יוצאת מהמכשיר של המבקר.",
  "The portrait is a file in the site's code (public/ariel-silas-*.jpg); replacing it is a code change.": "הדיוקן הוא קובץ בקוד האתר (public/ariel-silas-*.jpg); החלפתו היא שינוי בקוד.",
  "The privacy page changes its wording to match when you publish.": "דף הפרטיות משנה את הנוסח בהתאם כשתפרסמו.", "The same again": "שוב אותה סיסמה", "The site": "האתר", "The site will say:": "באתר ייכתב:",
  'The site\'s content is not in the admin yet. Open Publishing and choose "Import the current site".': "תוכן האתר עדיין לא בניהול. פתחו את פרסום ובחרו \"ייבוא האתר הנוכחי\".",
  "The sitemap, the language links between pages and the structured data for each piece are made by the site itself when it publishes.": "מפת האתר, הקישורים בין השפות והנתונים המובנים של כל תכשיט נוצרים על ידי האתר עצמו בכל פרסום.",
  "The story (in the piece window and on its page)": "הסיפור (בחלון התכשיט ובדף שלו)", "The two passwords are not the same.": "שתי הסיסמאות אינן זהות.",
  "Their access ends at once, they are signed out everywhere, and the account can no longer sign in.": "הגישה שלהם מסתיימת מיד, הם מנותקים מכל מקום, והחשבון לא יוכל עוד להיכנס.",
  "Their design (The Line)": "העיצוב שלהם (הקו)",
  "Their name, contact details, messages and notes are erased from every enquiry and quote. Counts and amounts stay. This cannot be undone.": "השם, פרטי הקשר, ההודעות וההערות שלהם נמחקים מכל פנייה והצעת מחיר. מספרים וסכומים נשארים. אי אפשר לבטל זאת.",
  "There are no unpublished changes.": "אין שינויים שלא פורסמו.", "There is no document at this address.": "אין מסמך בכתובת הזו.", "There is no page at this address.": "אין דף בכתובת הזו.", "There is no product at this address.": "אין מוצר בכתובת הזו.",
  "These figures are approved by the house": "הנתונים האלה מאושרים על ידי הבית", "These have changes that are saved but not live yet:": "באלה יש שינויים שנשמרו אבל עדיין לא באתר:",
  "These pages will use the new file in their drafts. Nothing changes on the site until you publish them.": "הדפים האלה ישתמשו בקובץ החדש בטיוטות שלהם. דבר לא משתנה באתר עד שתפרסמו אותם.",
  "These rates are approved": "השערים האלה מאושרים", "They now need an authenticator code to sign in.": "מעכשיו הם צריכים קוד אימות כדי להיכנס.",
  "They receive an email with a link to choose a password. The link works once.": "הם יקבלו אימייל עם קישור לבחירת סיסמה. הקישור פועל פעם אחת.",
  "This account has no access to the admin": "לחשבון הזה אין גישה לניהול",
  "This copy of the admin was built without the backend's address. Follow ADMIN_SETUP.md: create the Supabase project, add its address and publishable key to the repository's Actions variables, and publish once.": "הגרסה הזו של הניהול נבנתה בלי כתובת המערכת. פעלו לפי ADMIN_SETUP.md: צרו את פרויקט Supabase, הוסיפו את הכתובת והמפתח הציבורי למשתני ה־Actions של המאגר, ופרסמו פעם אחת.",
  "This does not look like an email address.": "זה לא נראה כמו כתובת אימייל.", "This is your draft on the real page. Visitors still see the published version.": "זו הטיוטה שלכם על הדף האמיתי. המבקרים עדיין רואים את הגרסה המפורסמת.",
  "This link has expired or was already used. Ask for a new one from the sign-in page.": "הקישור פג או שכבר נעשה בו שימוש. בקשו חדש מדף הכניסה.", "This page does not exist.": "הדף הזה אינו קיים.",
  "This piece is marked exceptional: the site does not show it in the collection grid or give it a page of its own. It is kept here as a record.": "התכשיט הזה מסומן כחריג: האתר אינו מציג אותו בגריד הקולקציה ואינו נותן לו דף משלו. הוא נשמר כאן לתיעוד.",
  "This quote was sent on {d}. Its amount and specification are fixed; to offer something else, withdraw it and make a new one.": "ההצעה נשלחה ב־{d}. הסכום והמפרט קבועים; כדי להציע משהו אחר, משכו אותה והכינו חדשה.",
  "This record was merged.": "הרשומה מוזגה.", "Times are Israel time. Figures cover the last 7 full days unless they say otherwise.": "השעות לפי שעון ישראל. הנתונים מכסים את 7 הימים המלאים האחרונים אלא אם צוין אחרת.",
  "Title": "כותרת", "Title (in the tab and in search results)": "כותרת (בלשונית ובתוצאות החיפוש)", "Title in search results": "כותרת בתוצאות החיפוש", "Title in search results (optional)": "כותרת בתוצאות החיפוש (לא חובה)",
  "Title in search results and the tab": "כותרת בתוצאות החיפוש ובלשונית", "To": "עד", "Top menu": "תפריט עליון", "Total carat weights offered": "משקלי קראט שמוצעים", "Try again": "נסו שוב",
  "Try starting the build again": "נסו להפעיל שוב את הבנייה", "Turn it on": "הפעלה", "Type": "סוג", "Under the name on the card": "מתחת לשם בכרטיס", "Unpublished changes": "שינויים שלא פורסמו",
  "Unsaved changes": "שינויים שלא נשמרו", "Unsaved work from earlier on this device was restored.": "עבודה שלא נשמרה מוקדם יותר במכשיר הזה שוחזרה.", "Uploading {f}…": "מעלים את {f}…",
  "Use a page on this site (like about/ or #concierge), or a full https:// address.": "השתמשו בדף באתר (כמו about/ או ‎#concierge), או בכתובת https://‎ מלאה.",
  "Use at least 10 characters.": "השתמשו בלפחות 10 תווים.", "Use lower-case letters, numbers and hyphens, like silavu-aura.": "השתמשו באותיות לטיניות קטנות, ספרות ומקפים, כמו silavu-aura.",
  "Use lower-case letters, numbers and hyphens.": "השתמשו באותיות לטיניות קטנות, ספרות ומקפים.",
  "Use this only when both records are the same person. Their enquiries and quotes move to this record; details missing here are taken from the other.": "השתמשו בזה רק כששתי הרשומות הן אותו אדם. הפניות והצעות המחיר עוברות לרשומה הזו; פרטים חסרים כאן נלקחים מהאחרת.",
  "Use this version": "שימוש בגרסה הזו", "Use {n}": "שימוש ב־{n}", "Used wherever the page does not give its own.": "משמש בכל מקום שבו הדף אינו מספק תיאור משלו.", "Valid for (days)": "תקף ל־(ימים)",
  "Valid until": "בתוקף עד", "Valid until {d}.": "בתוקף עד {d}.", "Value": "ערך", "Versions": "גרסאות", "View the site": "צפייה באתר", "Visit counting": "ספירת ביקורים", "Visits": "ביקורים",
  "Waiting for the build to start": "ממתינים לתחילת הבנייה", "Waiting…": "ממתין…", "What": "מה", "What changed": "מה השתנה", "What it is": "מה זה", "What it is for": "עבור מה",
  "What the bracelet builder offers. The 3D bracelet itself stays exactly as designed.": "מה כלי עיצוב הצמיד מציע. הצמיד התלת־ממדי עצמו נשאר בדיוק כפי שעוצב.",
  "What they asked": "מה ביקשו", "WhatsApp number": "מספר וואטסאפ", "WhatsApp, email and phone clicks": "לחיצות על וואטסאפ, אימייל וטלפון", "When": "מתי",
  "When a page's address changes, the old address forwards readers to the new one. (GitHub Pages cannot send a true redirect; the old address gets a small forwarding page that search engines understand.)": "כשכתובת של דף משתנה, הכתובת הישנה מעבירה את הקוראים לחדשה. (GitHub Pages אינו יכול לשלוח הפניה אמיתית; בכתובת הישנה מוצב דף העברה קטן שמנועי חיפוש מבינים.)",
  "Where": "היכן", "Where it is used": "היכן הוא בשימוש", "Where the figures come from": "מקור הנתונים", "Who": "מי",
  "With the backend connected, enquiries are saved here in the admin and the house is emailed through the mail settings in ADMIN_SETUP.md.": "כשהמערכת מחוברת, הפניות נשמרות כאן בניהול והבית מקבל אימייל לפי הגדרות הדואר ב־ADMIN_SETUP.md.",
  "With the country code, e.g. +972 50 000 0000. Empty: no WhatsApp option.": "עם קידומת המדינה, למשל ‎+972 50 000 0000. ריק: אין אפשרות וואטסאפ.",
  "Without approved, dated rates the estimate is shown in AED only. Rates are entered by hand; nothing is fetched live.": "בלי שערים מאושרים ומתוארכים ההערכה מוצגת בדירהם בלבד. השערים מוזנים ידנית; דבר אינו נמשך בזמן אמת.",
  "Word written large behind its window": "המילה שכתובה בגדול מאחורי החלון שלו", "Words": "מילים", "Wrist": "פרק יד", "Wrist sizes offered (cm)": "מידות פרק יד שמוצעות (ס״מ)", "Yes": "כן",
  "You have unsaved changes. Leave without saving? (A copy is kept on this device.)": "יש שינויים שלא נשמרו. לצאת בלי לשמור? (עותק נשמר במכשיר הזה.)",
  "You will sign in with your password only. If the owner requires a second factor for your account, you will lose access until you set one up again.": "תיכנסו עם הסיסמה בלבד. אם הבעלים דורשים אימות דו־שלבי לחשבון שלכם, תאבדו גישה עד שתגדירו אותו שוב.",
  "Your account needs a second factor": "החשבון שלכם צריך אימות דו־שלבי", "Your authenticator code": "קוד האימות", "Your name": "השם שלכם", "Your password is changed.": "הסיסמה שונתה.",
  "Your role does not include this part of the admin.": "התפקיד שלכם אינו כולל את החלק הזה של הניהול.",
  "anonymized": "אנונימי", "changed {when}": "שונה {when}", "choose files": "בחירת קבצים", "desktop": "מחשב", "draft": "טיוטה", "e.g. Bracelet": "למשל צמיד", "email not sent": "אימייל לא נשלח",
  "live": "באתר", "mobile": "נייד", "new": "חדש", "no": "לא", "overdue": "באיחור", "per session, while the page was in view": "לביקור, בזמן שהדף היה מוצג", "removed": "הוסר", "small": "קטן",
  "tablet": "טאבלט", "to be brought back": "יוחזר לאתר", "to be taken down": "יוסר מהאתר", "vs the 7 days before": "לעומת 7 הימים שלפני", "yes": "כן",
  "{a} of {b} counted sessions": "{a} מתוך {b} ביקורים שנספרו", "{a} to {b} (Israel time), compared with the same length of time before.": "{a} עד {b} (שעון ישראל), בהשוואה לתקופה באותו אורך שלפני.",
  "{a}–{b} of {n}": "{a}–{b} מתוך {n}", "{f}: larger than 50 MB.": "{f}: גדול מ־50MB.",
  "{f}: only JPEG, PNG, WebP, AVIF pictures and MP4 or WebM films can be added (SVG is not accepted).": "{f}: אפשר להוסיף רק תמונות JPEG, ‏PNG, ‏WebP, ‏AVIF וסרטוני MP4 או WebM (קובצי SVG אינם מתקבלים).",
  "{f}: this picture could not be read.": "{f}: לא ניתן לקרוא את התמונה.",
  "{f}: too small ({w}×{h}). The site needs at least 1254 pixels across for sharp product photographs.": "{f}: קטן מדי ({w}×{h}). האתר צריך לפחות 1254 פיקסלים לרוחב לצילומי מוצר חדים.",
  "{n} changed": "{n} שונו", "{n} changes": "{n} שינויים", "{n} enquiries": "{n} פניות", "{n} new or waiting for a follow-up.": "{n} חדשות או ממתינות למעקב.",
  "{n} saved changes are not live yet.": "{n} שינויים שמורים עדיין לא באתר.", "{n} sentences have no translation and show in English": "ל־{n} משפטים אין תרגום והם מוצגים באנגלית",
  "{o}: per carat at the reference size": "{o}: לקראט בגודל הייחוס",
  /* values shown through t() */
  "owner": "בעלים", "editor": "עורך", "support": "שירות", "analyst": "אנליסט", "Owner": "בעלים", "Editor": "עורך", "Support": "שירות", "Analyst": "אנליסט",
  "Everything, including the team, security, exports and restoring.": "הכול, כולל הצוות, האבטחה, הייצוא והשחזור.",
  "Products, pages, media and publishing. No customers, no team.": "מוצרים, דפים, מדיה ופרסום. בלי לקוחות ובלי צוות.",
  "Enquiries, customers and quotes. No publishing, no team, no bulk export.": "פניות, לקוחות והצעות מחיר. בלי פרסום, בלי צוות ובלי ייצוא גורף.",
  "Visit figures only. No names, no editing.": "נתוני ביקורים בלבד. בלי שמות ובלי עריכה.",
  "contacted": "נוצר קשר", "quoted": "נשלחה הצעה", "follow_up": "למעקב", "won": "נסגרה בהצלחה", "closed": "סגורה",
  "sent": "נשלחה", "accepted": "התקבלה", "declined": "נדחתה", "expired": "פגה", "withdrawn": "נמשכה",
  "lead": "פנייה", "client": "לקוח", "past_client": "לקוח בעבר",
  "email": "אימייל", "whatsapp": "וואטסאפ", "phone": "טלפון", "pending": "בבדיקה", "ready": "מוכן", "rejected": "נדחה",
  "white": "זהב לבן", "yellow": "זהב צהוב", "rose": "זהב ורוד", "platinum": "פלטינה",
  "Round": "עגול", "Oval": "אובל", "Cushion": "קושן", "Princess": "פרינסס", "Emerald": "אמרלד", "Marquise": "מרקיזה", "Pear": "טיפה", "Baguette": "באגט",
  "A piece from the collection": "תכשיט מהקולקציה", "Private viewing": "פגישה פרטית", "Bespoke commission": "תכשיט בהתאמה אישית",
  "Product": "מוצר", "Collection": "קולקציה", "Policy": "מסמך", "Page": "דף", "Other languages": "שפות נוספות", "imported": "יובא", "saved": "נשמר", "published": "פורסם", "restored": "שוחזר", "archived": "הועבר לארכיון",
  "Where visits came from": "מאיפה הגיעו הביקורים", "Campaign": "קמפיין", "First page": "דף ראשון", "Last page": "דף אחרון", "Pieces": "תכשיטים", "Browser": "דפדפן", "Language": "שפה", "Country": "מדינה",
  "Opened a piece": "פתחו תכשיט", "Started the form": "התחילו את הטופס", "Enquiry saved": "פנייה נשמרה", "Started designing": "התחילו לעצב", "Chose a design": "בחרו עיצוב",
  "Pieces opened": "תכשיטים שנפתחו", "Designs started": "עיצובים שהתחילו",
  "bracelets": "צמידים", "necklaces": "שרשראות", "rings": "טבעות", "earrings": "עגילים",
  "Each piece's title and description are set on its own page in Products, and a piece is shared with its first photograph.": "הכותרת והתיאור של כל תכשיט נקבעים בעמוד שלו במוצרים, ותכשיט משותף עם התצלום הראשון שלו.",
  "The picture when the site is shared": "התמונה כשמשתפים את האתר",
  "Shown by WhatsApp, Instagram, Facebook and others when someone shares the site. Best 1200 × 630 pixels. Without one, the designed SILAVU card is used.": "מוצגת ב־WhatsApp, באינסטגרם, בפייסבוק ובמקומות אחרים כשמישהו משתף את האתר. הכי טוב 1200 × 630 פיקסלים. בלי תמונה, משתמשים בכרטיס SILAVU המעוצב.",
  "Use the designed SILAVU card": "להשתמש בכרטיס SILAVU המעוצב",
  "The designed SILAVU card": "כרטיס SILAVU המעוצב",
  "Published. GitHub checks for new releases every few minutes; the site is usually live within 10 to 15 minutes.": "פורסם. GitHub בודק פרסומים חדשים כל כמה דקות; האתר מתעדכן בדרך כלל תוך 10 עד 15 דקות.",
  "GitHub checks for new releases every few minutes, so the build starts on its own within about ten minutes.": "GitHub בודק פרסומים חדשים כל כמה דקות, כך שהבנייה מתחילה מעצמה תוך כעשר דקות.",
  "Waiting for GitHub's next check; it starts on its own within about ten minutes.": "ממתין לבדיקה הבאה של GitHub; הבנייה תתחיל מעצמה תוך כעשר דקות.",
  "starts at once": "מתחיל מיד",
  "GitHub checks every few minutes": "GitHub בודק כל כמה דקות",
  "Set a password": "קביעת סיסמה",
  "{e} can sign in now with the password you set.": "{e} יכול/ה להיכנס עכשיו עם הסיסמה שקבעתם.",
  "Add them": "הוספה",
  "Password (optional)": "סיסמה (לא חובה)",
  "Empty: they get an email with a link to choose their own. With a password: the account is ready at once and no email is sent; give them the password yourself and ask them to change it under Account.": "ריק: יישלח אימייל עם קישור לבחירת סיסמה. עם סיסמה: החשבון מוכן מיד ולא נשלח אימייל; מסרו את הסיסמה בעצמכם ובקשו להחליף אותה בחשבון.",
  "Password set. Give it to them yourself.": "הסיסמה נקבעה. מסרו אותה בעצמכם.",
  "A new password for {n}": "סיסמה חדשה עבור {n}",
  "Set the password": "קביעת הסיסמה",
  "At least 10 characters. Nothing is emailed; give it to them yourself.": "לפחות 10 תווים. לא נשלח אימייל; מסרו אותה בעצמכם.",
  "If no email arrives, the owner can set a new password for you under Team.": "אם לא מגיע אימייל, הבעלים יכולים לקבוע לכם סיסמה חדשה במסך הצוות.",
  "You will be signed out in a minute because nothing has happened for a while. Click anywhere to stay.": "בעוד דקה תתבצע יציאה מהחשבון כי לא הייתה פעילות זמן מה. לחצו בכל מקום כדי להישאר.",
  "Delete your account?": "למחוק את החשבון שלכם?",
  "Your sign-in is deleted for good and you lose access at once. What you wrote and published stays on the site and in the history.": "פרטי הכניסה שלכם נמחקים לצמיתות והגישה נחסמת מיד. מה שכתבתם ופרסמתם נשאר באתר ובהיסטוריה.",
  "Delete my account": "מחיקת החשבון שלי",
  "Type DELETE to confirm. The only owner cannot delete their account: make someone else owner first.": "הקלידו DELETE לאישור. הבעלים היחידים לא יכולים למחוק את החשבון: קודם הגדירו מישהו אחר כבעלים.",
  "Type DELETE": "הקלידו DELETE",
  "Offensive words": "מילים פוגעניות",
  "offensive words": "מילים פוגעניות",
  "This enquiry contains words that look offensive ({w}). It is kept like any other; read it with care.": "הפנייה הזו כוללת מילים שנראות פוגעניות ({w}). היא נשמרת כמו כל פנייה אחרת; קראו אותה בזהירות.",
  "You were signed out after 30 minutes without activity. Anything you had not saved is kept on this device.": "יצאתם מהחשבון אחרי 30 דקות ללא פעילות. מה שלא נשמר נשמר על המכשיר הזה.",
  "This is an affiliate or paid link": "זהו קישור שותפים או קישור ממומן",
  "The link then says so on the site (\"Affiliate link\" / \"קישור שותפים\"), opens in a new tab and tells search engines it is sponsored.": "הקישור יציין זאת באתר (\"Affiliate link\" / \"קישור שותפים\"), ייפתח בלשונית חדשה ויסומן למנועי חיפוש כממומן.",
};
