import { chromium } from "playwright-core";
const O="/tmp/claude-0/-home-user-isracard/cbce1d7f-fb80-59fc-b523-1be1a454b815/scratchpad/m/";
const b=await chromium.launch({executablePath:"/opt/pw-browsers/chromium-1194/chrome-linux/chrome",args:["--no-sandbox"]});
let pass=0,fail=0; const ok=(c,m)=>{c?pass++:fail++; console.log((c?"PASS ":"FAIL ")+m);};
const p=await (await b.newContext({viewport:{width:1440,height:900}})).newPage(); const errs=[]; p.on("pageerror",e=>errs.push(e.message));
await p.route(/fonts\./,r=>r.abort()); await p.goto("http://localhost:8777/",{waitUntil:"load"}); await p.waitForTimeout(1200); await p.click("#enterBtn",{timeout:2000}).catch(()=>{});
await p.evaluate(()=>{document.documentElement.style.scrollBehavior="auto"; document.querySelector(".pgrid").scrollIntoView({block:"center"});}); await p.mouse.move(5,5); await p.waitForTimeout(8000);
const rest=await p.evaluate(()=>[...document.querySelectorAll(".pgrid .piece:not(.soon)")].map(pc=>({hx:pc.querySelectorAll(".im.hx.on").length, sig:!!pc.querySelector(".k.sig"), dots:pc.querySelectorAll(".swd i").length, on:[...pc.querySelectorAll(".swd i")].findIndex(d=>d.classList.contains("on"))})));
ok(rest.every(r=>r.hx===0 && !r.sig && r.on===0 && r.dots>=4), "at rest every card shows its first photograph, no reference line "+JSON.stringify(rest));
await p.screenshot({path:O+"cards-rest.jpg",type:"jpeg",quality:60});
const box=await p.evaluate(()=>{const r=document.querySelector("#p-ring .fig").getBoundingClientRect(); return {x:r.left+r.width/2,y:r.top+r.height/2};});
await p.mouse.move(box.x,box.y); await p.waitForTimeout(2600);
const h=await p.evaluate(()=>{const pc=document.getElementById("p-ring"); return {on:[...pc.querySelectorAll(".swd i")].findIndex(d=>d.classList.contains("on")), hx:pc.querySelectorAll(".im.hx").length, vis:pc.querySelectorAll(".im.hx.on").length};});
ok(h.on>=1 && h.vis===1 && h.hx>=3, "hover walks through the other photographs "+JSON.stringify(h));
await p.screenshot({path:O+"cards-hover.jpg",type:"jpeg",quality:60});
await p.mouse.move(5,5); await p.waitForTimeout(900);
const back=await p.evaluate(()=>document.querySelectorAll("#p-ring .im.hx.on").length);
ok(back===0, "leaving puts the first photograph back");
ok(errs.length===0, "no errors "+errs.join("|"));
await b.close(); console.log(pass,"pass,",fail,"fail");
