import { chromium } from "playwright-core";
const b = await chromium.launch({ executablePath:"/opt/pw-browsers/chromium-1194/chrome-linux/chrome", args:["--no-sandbox","--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader"] });
const p = await b.newPage({ viewport:{width:1440,height:900} }); await p.emulateMedia({ reducedMotion: "reduce" }); const errs=[]; p.on("pageerror", e => errs.push(e.message)); p.on("console", m => { if (m.type()==="error") errs.push("console:"+m.text().slice(0,120)); });
await p.goto("file:///home/user/isracard/lumera/site/silavu-page.html", { waitUntil:"load" }); await p.waitForTimeout(1200); await p.click("#enterBtn").catch(()=>{}); await p.waitForTimeout(900);
const tick = async () => p.evaluate(() => new Promise(r => { let n = 0; const t0 = performance.now(); (function s() { n++; if (performance.now() - t0 < 500) requestAnimationFrame(s); else r(n); })(); }));
await p.evaluate(() => window.scrollTo({top: scrollY + document.getElementById("partners").getBoundingClientRect().top, behavior:"instant"})); await p.waitForTimeout(900);
console.log("after partners:", await p.evaluate(() => document.getElementById("whereT").textContent), "rAF/0.5s:", await tick());
await p.evaluate(() => { const pin = document.getElementById("stonepin"); window.scrollTo({top: scrollY + pin.getBoundingClientRect().top + (pin.offsetHeight - innerHeight) * 0.4, behavior:"instant"}); }); await p.waitForTimeout(900);
console.log("at pin:", await p.evaluate(() => document.getElementById("whereN").textContent + " boxp=" + window.__box.p), "rAF/0.5s:", await tick(), errs);
await b.close();
