import { chromium } from "playwright-core";
const OUT="/tmp/claude-0/-home-user-isracard/cbce1d7f-fb80-59fc-b523-1be1a454b815/scratchpad/qa";
import fs from "node:fs"; fs.mkdirSync(OUT,{recursive:true});
const b = await chromium.launch({ executablePath:"/opt/pw-browsers/chromium-1194/chrome-linux/chrome", args:["--no-sandbox","--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader"] });
const mob = process.argv[2]==="mob";
const tag = mob?"m":"d";
const p = await b.newPage({ viewport: mob?{width:390,height:844}:{width:1440,height:900}, isMobile:mob, hasTouch:mob });
await p.goto("file:///home/user/isracard/lumera/site/silavu-page.html",{waitUntil:"load"});
await p.waitForTimeout(3200); await p.click("#enterBtn",{timeout:4000}).catch(()=>{});
await p.waitForTimeout(1200);
const shot = async (n)=>{ await p.waitForTimeout(800); await p.screenshot({path:`${OUT}/${tag}-${n}.png`}); };
await shot("hero");
const go = async (id)=>{ await p.evaluate(i=>{const e=document.getElementById(i); e&&window.scrollTo({top:scrollY+e.getBoundingClientRect().top,behavior:"instant"});}, id); await p.waitForTimeout(900); };
await go("collection"); await shot("collection");
await go("build");
await p.evaluate(()=>{const t=[...document.querySelectorAll("#build a,#build button")].find(e=>/START DESIGNING/i.test(e.textContent));t&&t.click();});
await p.waitForTimeout(5000); await shot("builder-front");
await p.evaluate(()=>{const t=document.querySelector('[data-vpos="under"]'); t&&t.click();});
await p.waitForTimeout(3000); await shot("builder-under");
await go("wrist"); await shot("wrist");
await go("concierge"); await shot("concierge");
await go("end"); await shot("footer");
console.log(tag+" captured");
await b.close();
