import { chromium } from "playwright-core";
const b=await chromium.launch({executablePath:"/opt/pw-browsers/chromium-1194/chrome-linux/chrome",args:["--no-sandbox","--disable-background-networking","--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader","--ignore-gpu-blocklist"]});
const p=await (await b.newContext({viewport:{width:1440,height:900}})).newPage(); await p.route(/fonts\.(googleapis|gstatic)\.com/,r=>r.abort());
p.on("pageerror",e=>console.log("ERR",e.message)); p.on("console",m=>{ if(m.text().startsWith("EV")) console.log(m.text()); });
await p.goto("http://localhost:8777/",{waitUntil:"load"}); await p.waitForTimeout(1500); await p.click("#enterBtn",{timeout:3000}).catch(()=>{}); await p.waitForTimeout(800);
await p.evaluate(()=>{document.documentElement.style.scrollBehavior="auto"; document.getElementById("configure").scrollIntoView();}); await p.waitForTimeout(3000);
await p.evaluate(()=>document.querySelector('[data-toy="up"]').click()); await p.waitForTimeout(2500);
await p.click("#snakeback"); await p.waitForTimeout(2000); console.log("closed1", await p.evaluate(()=>window.__snakeState()), await p.evaluate(()=>document.documentElement.className));
await p.evaluate(()=>document.querySelector('[data-toy="up"]').click()); await p.waitForTimeout(1700);
console.log("open2", await p.evaluate(()=>window.__snakeState()), await p.evaluate(()=>document.documentElement.className));
await p.evaluate(()=>{ const v=document.getElementById("snakeveil"); ["pointerdown","pointerup","click"].forEach(t=>v.addEventListener(t,e=>console.log("EV",t,e.clientX,e.clientY,Math.round(e.timeStamp),window.__snakeState()),true)); });
console.log("phase", await p.evaluate(()=>window.__snakeState()), "hit", await p.evaluate(()=>{const e=document.elementFromPoint(720,450); return e.id||e.tagName;}));
await p.mouse.click(720,450); await p.waitForTimeout(2500);
console.log("after", await p.evaluate(()=>window.__snakeState()));
await b.close();
