import { chromium } from "playwright-core";
const OUT = "/tmp/claude-0/-home-user-isracard/cbce1d7f-fb80-59fc-b523-1be1a454b815/scratchpad";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome", args: ["--no-sandbox", "--use-gl=angle", "--use-angle=swiftshader", "--enable-unsafe-swiftshader"] });
const p = await b.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 2 });
await p.goto("http://127.0.0.1:8777/", { waitUntil: "domcontentloaded" });
await p.waitForTimeout(2400); await p.click("#enterBtn").catch(()=>{});
await p.waitForTimeout(700);
await p.evaluate(async () => { const s = Math.round(innerHeight*0.8); for (let y=0;y<document.body.scrollHeight;y+=s){scrollTo({top:y,behavior:"instant"});await new Promise(r=>setTimeout(r,70));} });
await p.evaluate(() => document.getElementById("stripwrap").scrollIntoView({ block:"center", behavior:"instant" }));
await p.waitForTimeout(2200);
const el = await p.$("#stripwrap");
await el.screenshot({ path: `${OUT}/pill-line.png` });
const t = await p.$$(".vt .vtb"); if (t[1]) await t[1].click();
await p.waitForTimeout(2600);
await p.evaluate(() => document.getElementById("stripwrap").scrollIntoView({ block:"center", behavior:"instant" }));
await p.waitForTimeout(900);
await (await p.$("#stripwrap")).screenshot({ path: `${OUT}/pill-wrist.png` });
console.log("shot");
await b.close();
