import { chromium } from "playwright-core";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome", args: ["--no-sandbox", "--use-gl=angle", "--use-angle=swiftshader", "--enable-unsafe-swiftshader"] });
const p = await b.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 2 });
await p.goto("http://127.0.0.1:8777/", { waitUntil: "domcontentloaded" });
await p.waitForTimeout(2400); await p.click("#enterBtn").catch(()=>{});
await p.waitForTimeout(700);
await p.evaluate(async () => { const s = Math.round(innerHeight*0.8); for (let y=0;y<document.body.scrollHeight;y+=s){scrollTo({top:y,behavior:"instant"});await new Promise(r=>setTimeout(r,70));} });
await p.evaluate(() => document.getElementById("stripwrap").scrollIntoView({ block:"start", behavior:"instant" }));
await p.waitForTimeout(600);
const t = await p.$$(".vt .vtb"); if (t[1]) await t[1].click();
await p.waitForTimeout(2500);
const rep = async (label) => console.log(label, await p.evaluate(() => {
  const g = id => { const e = typeof id === "string" ? document.querySelector(id) : id; if (!e) return "missing";
    const r = e.getBoundingClientRect(); const cs = getComputedStyle(e);
    return `${Math.round(r.width)}x${Math.round(r.height)} top=${Math.round(r.top)} pos=${cs.position} ${cs.display===("none")?"HIDDEN":""}`; };
  return JSON.stringify({ scrollY: Math.round(scrollY), strip: g("#stripwrap"), bar: g("#handbar"), opts: g("#opts"), total: g(".total") }, null, 0);
}));
await rep("at top:");
await p.evaluate(() => scrollBy({ top: 500, behavior: "instant" })); await p.waitForTimeout(500);
await rep("after 500:");
await b.close();
